- name: Install requiered packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add docker-ce repository
  shell:  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Start docker
  systemd:
    state: started
    name: docker
    enabled: yes

- name: Get docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /bin/docker-compose

- name: Set executable
  shell: chmod +x /bin/docker-compose
